package scan

import (
	"context"
	"testing"
)

func TestCargoDetector(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "Cargo.lock", `# This file is automatically @generated by Cargo.

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.40.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
foo = "bar"
`)
	d := &cargoDetector{}
	out, err := d.Detect(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 2 {
		t.Fatalf("expected 2 cargo packages, got %d", len(out))
	}
	if out[0].Purl != "pkg:cargo/serde@1.0.210" {
		t.Errorf("unexpected first purl: %s", out[0].Purl)
	}
	if out[1].Version != "1.40.0" {
		t.Errorf("expected tokio 1.40.0, got %s", out[1].Version)
	}
}

func TestCargoNoLockfile(t *testing.T) {
	dir := t.TempDir()
	d := &cargoDetector{}
	out, err := d.Detect(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 0 {
		t.Fatalf("expected 0 components, got %d", len(out))
	}
}

func TestMavenDetector(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "pom.xml", `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.14.1</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>5.3.20</version>
    </dependency>
    <dependency>
      <groupId>org.junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>`)
	d := &mavenDetector{}
	out, err := d.Detect(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 3 {
		t.Fatalf("expected 3 maven dependencies, got %d", len(out))
	}
	// Property refs normalise to "managed".
	var seenManaged bool
	for _, c := range out {
		if c.Name == "junit" && c.Version == "managed" {
			seenManaged = true
		}
	}
	if !seenManaged {
		t.Error("expected junit to resolve version 'managed'")
	}
	if out[0].Purl != "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1" {
		t.Errorf("unexpected first purl: %s", out[0].Purl)
	}
}
