apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - dragonfly.yaml
  - nats.yaml
  - api.yaml
  - scanner.yaml
  - analyzer.yaml
  - web.yaml

commonLabels:
  app.kubernetes.io/name: sentinel
  app.kubernetes.io/managed-by: kustomize
